# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_1', models.CharField(default='-', max_length=200)),
                ('forecast_2', models.CharField(default='-', max_length=200)),
                ('forecast_3', models.CharField(default='-', max_length=200)),
                ('forecast_4', models.CharField(default='-', max_length=200)),
                ('forecast_5', models.CharField(default='-', max_length=200)),
                ('forecast_6', models.CharField(default='-', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature_1', models.FloatField(default='-')),
                ('average_temperature_2', models.FloatField(default='-')),
                ('average_temperature_3', models.FloatField(default='-')),
                ('average_temperature_4', models.FloatField(default='-')),
                ('average_temperature_5', models.FloatField(default='-')),
                ('average_temperature_6', models.FloatField(default='-')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
    ]
